language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
env:
    - TWIG_VERSION="^1.0@stable"
    - TWIG_VERSION="^2.0@dev"

matrix:
    exclude:
        - php: 5.3
          env: TWIG_VERSION="^2.0@dev"
        - php: 5.4
          env: TWIG_VERSION="^2.0@dev"

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar require twig/twig:"${TWIG_VERSION}"
    - php composer.phar install

script:
    - phpunit --coverage-text

notifications:
    email:
        - innovation@igraal.com
